version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    container_name: mongodb-server
    ports:
      - 27017:27017
    volumes:
      - ./dataset/:/dataset
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: project

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-ui
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    links:
    - "mongo"